### ISSUE TITLE
Adding Max to Dartist!

### ISSUE THREAD

**Issue by mythz** [dartist/express#10]
Hey all @financeCoding @enyo 

I'm adding @MaxHorstmann to the team, Max is a great dev I work with at StackExchange who I've convinced to get into Dart :) he's already submitting helpful pull-reqs, so adding to the team so he can continue his good work more freely.

Cheers,

**Comment by adam-singer** [comment]
sgtm, Welcome @MaxHorstmann :+1:

**Comment by MaxHorstmann** [comment]
thx guys!

**Comment by enyo** [comment]
Welcome @MaxHorstmann
