### ISSUE TITLE
dartmixins - instance field may not be 'const'

### ISSUE THREAD

**Issue by pawel-kaminski-krk** [dartist/express#13]
I get this error while running app

```
'package:dartmixins/src/mixin.dart': error: line 271 pos 13: instance field may not be 'const'
  const int _PAD_LEFT = 1;
```

it is around for few months now. are you going to release anything soon to make express and jaded work with new sdk or are you waiting for pull request with fix.

do you know how I can fix it - which lib should I use now?, it probably easier for me to change your code and push it to rather than start from scratch as I am quite familiar with nodejs's express.

**Comment by mythz** [comment]
You can send a pull request if you want to fix it, but I recommend using another OSS project, as I wont have any time to dedicate to resolving any issues for any of my Dart projects for the foreseeable future - My time is 24/7 dedicated to running a new Startup.

**Comment by pawel-kaminski-krk** [comment]
fair enough.

so you are not using dart for it I guess ;-) good luck

**Comment by mythz** [comment]
thx, yeah Dart was a fun hobby for the old me who had time for hobbies :)

**Comment by adracus** [comment]
Was fixed, dartmixins is no longer a dependency.
