### ISSUE TITLE
Multiple callbacks in route

### ISSUE THREAD

**Issue by SamVerschueren** [dartist/express#16]
In Express it is possible to add multiple callbacks to a route, this is nice because you can add preconditions easily before the request is handled by a controller (for instance check if a user is signed in).

``` JavaScript
app.get('/dashboard', middleware.isSignedIn, dashboard.index);
```

It would be nice to have the same functionality in this library. I'm willing to take a look towards the possibilities.

**Comment by mythz** [comment]
Sure we'd take a pull request for something like this.

**Comment by SamVerschueren** [comment]
Oké thanks. Is the goal of the project to copy all the express features and method names (in order for Node devs to get them quickly going) or isn't it that strict? Would be cool though...

**Comment by mythz** [comment]
Nah doesn't have to be an exact match, if there's idioms that would make more sense for Dart we should use those instead. i.e. its not normal in Dart to have method overloading of positional arguments, as named params should be preferred or maybe we can extend HttpContext to look something like:

``` dart
app.get('/dashboard', (HttpContext ctx) {
    ctx.use(middleware.isSignedIn)
      ..use(dashboard.index);
});
```

**Comment by SamVerschueren** [comment]
I thought that Dart had support for variable arguments but they don't so we have to do it differently, something like you posted. Although I don't find that a proper solution. When I build Node apps, I always create a Router class. In Dart I do it like this

``` Dart
import '../controllers/HomeController.dart';

class Router {

    HomeController home;

    Router() {
        home = new HomeController();
    }

    void register(Express app) {
        app.get('/', home.index);
        app.post('/contact', home.contact);
    }
}
```

By using your method it would become something like this if you want middleware.

``` Dart
import '../middleware/MyMiddleware.dart';
import '../controllers/HomeController.dart';

class Router {

    MyMiddleware middleware;
    HomeController home;

    Router() {
        middleware = new MyMiddleware();
        home = new HomeController();
    }

    void register(Express app) {
        app.get('/', (ctx) {
            ctx.use(middleware.isSignedIn)
                ..use(home.index);
        });
        app.post('/contact', home.contact);
    }
}
```

Maybe it's cleaner to do it like this

``` Dart
import '../middleware/MyMiddleware.dart';
import '../controllers/HomeController.dart';

class Router {

    MyMiddleware middleware;
    HomeController home;

    Router() {
        middleware = new MyMiddleware();
        home = new HomeController();
    }

    void register(Express app) {
        app.get('/').then(middleware.isSignedIn).then(home.index);
        app.post('/contact', home.contact);
    }
}
```

And working with the same next parameter as in NodeJS.

``` Dart
class MyMiddleware {
   void isSignedIn(HttpContext ctx, Function next) {
       // Check if the user is signed in

       next();
   }
}
```

Or another proper solution could be

``` Dart
class MyMiddleware {
   bool isSignedIn(HttpContext ctx) {
       // Check if the user is signed in

       return true;
   }
}
```

If the middleware returns true, continue to the next handler, otherwise it will stop? Maybe the latest with the boolean is the cleanest.

Let me know what you guys think of it.

**Comment by SamVerschueren** [comment]
Implemented it in https://github.com/SamVerschueren/express/tree/iss16. Can you guys have a look and give feedback.

Have to add documentation. But will wait for feedback and adjust things if necessary.
