### ISSUE TITLE
How to get the posted data?

### ISSUE THREAD

**Issue by freewind** [dartist/express#6]
I mean a form in HTML:

```
<form method="post">
<input type="text" name="title" />
<input type="submit" />
</form>
```

How to get the value of posted `title`?

**Comment by mythz** [comment]
Unfortunately Dart's HttpRequest doesn't provide an option for this, so it's something we'd need to bake inside of the framework ourselves. 

I'll leave this open as a feature request.

**Comment by SamVerschueren** [comment]
I will make a pull request for this. I managed to get the post data as map quite easily. Will do something like this

``` Dart
app.post('/form', (ctx) {
    print(ctx.body['title']);
});
```

So ctx.body is a map (key-value pair) holding the name as key and offcourse the content of the field as value.
